# Generated by Django 4.2 on 2023-06-15 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_name', models.CharField(max_length=255)),
                ('prod_price', models.CharField(max_length=255)),
                ('doc_image', models.ImageField(upload_to='product')),
            ],
        ),
    ]
