# Generated by Django 4.2 on 2023-06-15 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='doc_image',
            new_name='prod_image',
        ),
    ]
