# Generated by Django 4.2 on 2023-07-21 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_customer_order_shippingaddress_orderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='prod_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='prod_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='prod_price',
            new_name='price',
        ),
    ]
