# Generated by Django 4.2 on 2023-07-21 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_prod_image_product_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='prod_image',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='prod_name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='prod_price',
        ),
    ]
