# Generated by Django 4.2 on 2023-07-28 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_image_product_prod_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='transaction_id',
            new_name='orderID',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='order',
            new_name='orderID',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='order',
            new_name='orderID',
        ),
    ]
