# Generated by Django 4.2 on 2023-08-01 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_rename_transaction_id_order_orderid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='orderID',
        ),
    ]
